name: ValorantMC
version: ${project.version}
main: xyz.destiall.mc.valorant.Main
api-version: 1.17
authors: [ destiall ]
description: Valorant in Minecraft!
depend:
  - WorldEdit
  - ProtocolLib
softdepend:
  - CrackShot
commands:
  valorant:
    aliases:
      - vmc
  globalchat:
    aliases:
      - g
  teamchat:
    aliases:
      - t