name: ValorantMC
version: ${project.version}
main: xyz.destiall.mc.valorant.Main
api-version: 1.17
authors: [ destiall ]
description: Valorant in Minecraft!
depend:
  - WorldEdit
  - CrackShot
commands:
  valorant:
    aliases:
      - vmc
    permission: valorant.admin